spring:
  datasource:
    url: jdbc:h2:file:./data/clouddb
    driver-class-name: org.h2.Driver
    username: sa
    password: 12

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql
#      continue-on-error: true

  h2:
    console:
      enabled: true
      path: /h2-console

#    servlet:
#      multipart:
#        max-file-size: 100MB
#        max-request-size: 100MB

server:
  port: 8080
#  servlet:
#    context-path: /cloud

#cloud:
#  storage-path: ./cloud-storage
#  token-prefix: "Bearer "
#  token-min-length: 10